### ISSUE TITLE
publish npm package

### ISSUE THREAD

**Issue by kevinbarabash** [Khan/translation-assistant#16]
This will allow us to avoid checking in build files into the repo which avoid situations where the source code has been updated but the built files haven't.

**Comment by danielhollas** [comment]
Hi @mpolyak. Just wanted to ask, if we were to publish the npm package for Translation Assistant, would it make deploying future PRs into webapp easier?

I would like to get this done eventually because I am now reusing some code from here in a [browser plugin for KA translators](https://international-forum.khanacademy.org/t/khan-academy-dots-plugin-autotranslate-math-in-crowdin-window/1441), and npm package would make it easier for me to maintain it. So I am just trying to understand other benefits/costs of this and think about whether to prioritize this before other PRs here.

Thanks!

**Comment by danielhollas** [comment]
In my plugin, I integrated TA as a git submodule and it does the trick for now.

**Comment by danielhollas** [comment]
To mitigate the issue with build files, we could also use a `pre-commit` node module as was done in khan/live-editor#673. Since I'll be working on a couple things for this repo in near future, I'll submit a PR for this first.
